### ISSUE TITLE
`mkdir` error if filename containt space(s)

### ISSUE THREAD

**Issue by xerc** [zachleat/glyphhanger#18]
**ver. 5.0.0**
https://github.com/zachleat/glyphhanger/blob/6b273801534493b18f570f30dce1c6cf7bfa0660/src/GlyphHangerFontFace.js#L84
zsh@osx
```
$ glyphhanger --subset="New Font.ttf" --formats=woff,woff2,woff-zopfli --json --css
$ glyphhanger --subset=New\ Font.ttf --formats=woff,woff2,woff-zopfli --json --css
```
```
Writing CSS file: New Font.css
GlyphHangerFontFace Error:  Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (node:fs:1389:3)
    at GlyphHangerFontFace.writeCSSFiles (/usr/local/lib/node_modules/glyphhanger/src/GlyphHangerFontFace.js:84:7)
    at /usr/local/lib/node_modules/glyphhanger/cmd.js:143:14 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT'
```

**Comment by lloydjatkinson** [comment]
I also get this and fixed it with:

```diff
--- subset=inter-v3-latin-regular.woff2 --formats=woff2 --css
+++ subset=./inter-v3-latin-regular.woff2 --formats=woff2 --css
```
